trigger: [main]
pr: [main]

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 20.x
      checkLatest: true
  - script: npx -y prettier --check .
    displayName: 'Lint: Prettier'
