jobs:
  - job:
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build dacpac
        inputs:
          command: 'build'
          projects: '**/*.sqlproj'
          arguments: '/p:OutDir=$(Build.BinariesDirectory) /p:AssemblyName=$(Build.Repository.Name) /p:SqlTargetName=$(Build.Repository.Name)'

      - publish: $(Build.BinariesDirectory)
        displayName: 'Publish dacpac artifact'
        condition: ne(variables['Build.Reason'], 'PullRequest')
        artifact: $(Build.Repository.Name)
