parameters:
- name: connectionStringName
  type: string
- name: azureServiceConnection
  type: string
- name: paasEnvironment
  type: string
- name: pool
  type: string
- name: keyVaultName
  type: string
  
jobs:
- template: jobs/deploy/request-azdo-agent.yml@pipeline-templates-paas2
  parameters:
    azureServiceConnection: '${{ parameters.azureServiceConnection }}'
    environment: '${{ parameters.paasEnvironment }}'
    entityCode: 'esm'

- job:
  pool: '${{ parameters.pool }}'
  steps: 
  - task: DownloadBuildArtifacts@1
    displayName: Download artifact
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '$(Build.Repository.Name)'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureKeyVault@2
    displayName: 'Get connection string from key vault'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnection }}'
      KeyVaultName: '${{ parameters.keyVaultName }}'
      SecretsFilter: '${{ parameters.connectionStringName }}'
  
  - task: PowerShell@2
    displayName: 'Deploy SQL database'
    inputs:
      targetType: 'inline'
      script: |
        dotnet new tool-manifest
        dotnet tool install microsoft.sqlpackage
        dotnet tool run sqlpackage /Action:Publish /SourceFile:$(System.ArtifactsDirectory)/$(Build.Repository.Name)/$(Build.Repository.Name).dacpac `
        /TargetConnectionString:"$(${{ parameters.connectionStringName }})"