parameters:
- name: connectionStringNameDev
  type: string
- name: connectionStringNameUat
  type: string
- name: connectionStringNameProd
  type: string
- name: tribe
  type: string
  values:
  - 'enabler'
  - 'client'
  - 'user'
- name: allowDataLoss
  type: boolean
  default: false
      
stages:
- stage: build
  displayName: Build
  jobs:
  - template: ./build.yaml@pipelines

- stage: deployDev
  displayName: 'Deploy to Dev'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - template: ./deploy.yaml@pipelines
    parameters:
      connectionStringName: '${{ parameters.connectionStringNameDev }}'
      azureServiceConnection: 'Azure_DEV'
      environment: 'dev'
      paasEnvironment: 'DEV'
      pool: 'SmartER-dev'
      keyVaultName: 'esm-app-integ-1-kv-d'
      allowDataLoss: ${{ parameters.allowDataLoss }}

- stage: deployUat
  displayName: 'Deploy to Uat'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
  dependsOn: ["build"]
  jobs:
  - deployment: 
    environment: 'uat-${{ parameters.tribe }}'
  - template: ./deploy.yaml@pipelines
    parameters:
      connectionStringName: '${{ parameters.connectionStringNameUat }}'
      azureServiceConnection: 'Azure_UAT'
      environment: 'uat'
      paasEnvironment: 'UAT'
      pool: 'SmartER-uat'
      keyVaultName: 'esm-app-integ-1-kv-u'
      allowDataLoss: ${{ parameters.allowDataLoss }}

- stage: deployProd
  displayName: 'Deploy to Prod'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: 
    environment: 'prd-${{ parameters.tribe }}'
  - template: ./deploy.yaml@pipelines
    parameters:
      connectionStringName: '${{ parameters.connectionStringNameProd }}'
      azureServiceConnection: 'Azure_PROD'
      environment: 'prod'
      paasEnvironment: 'PROD'
      pool: 'SmartER-prd'
      keyVaultName: 'esm-app-integ-1-kv-p'
      allowDataLoss: ${{ parameters.allowDataLoss }}